name: barterit2
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <4.0.0'

dependencies:
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5
  fluttertoast: ^8.2.2
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  google_fonts: ^4.0.4
  google_maps_flutter: ^2.3.1
  http: ^0.13.6
  image_cropper: ^4.0.1
  image_picker: ^0.8.7+5
  info_popup: ^3.0.4
  intl: ^0.18.1
  shared_preferences: ^2.1.1
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
